import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: { padding: 20, paddingTop: 60, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF' },
  backBtn: { marginRight: 15 },
  backBtnText: { color: '#2E7D32', fontWeight: 'bold', fontSize: 16 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#1A1A1A' },
  migrationAlert: { backgroundColor: '#FFF3E0', margin: 20, marginBottom: 0, padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#FFB74D' },
  migrationAlertTitle: { fontSize: 14, fontWeight: 'bold', color: '#E65100', marginBottom: 4 },
  migrationAlertText: { fontSize: 12, color: '#666', lineHeight: 18 },
  cardInfo: { backgroundColor: '#FFF', margin: 20, padding: 20, borderRadius: 20, elevation: 2 },
  petProfile: { flexDirection: 'row', alignItems: 'center', marginBottom: 25 },
  avatarPlaceholder: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#E8F5E9', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  petName: { fontSize: 22, fontWeight: 'bold', color: '#1A1A1A' },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, alignSelf: 'flex-start', marginTop: 5 },
  badgeSuccess: { backgroundColor: '#E8F5E9' },
  badgeWait: { backgroundColor: '#FFF3E0' },
  badgeText: { fontSize: 12, fontWeight: 'bold', color: '#2E7D32' },
  detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  detailItem: { width: '45%', marginBottom: 15 },
  detailLabel: { fontSize: 12, color: '#666', marginBottom: 2 },
  detailValue: { fontSize: 15, fontWeight: '600', color: '#333' },
  section: { padding: 20 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 20, color: '#1A1A1A' },
  vaccineItem: { flexDirection: 'row', marginBottom: 0 },
  timeline: { alignItems: 'center', marginRight: 15, width: 20 },
  dot: { width: 12, height: 12, borderRadius: 6, zIndex: 1 },
  dotActive: { backgroundColor: '#2E7D32' },
  vaccineContent: { flex: 1, paddingBottom: 25 },
  vaccineName: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  vaccineDate: { fontSize: 14, color: '#666', marginTop: 2 },
  helpBtn: { margin: 20, padding: 15, alignItems: 'center' },
  helpBtnText: { color: '#2E7D32', fontWeight: '600' }
});
